### ISSUE TITLE
Selection mechanics feel off

### ISSUE THREAD

**Issue by winkler1** [azazdeaz/transhand#1]
Hi-
 Playing with the demo, I keep butting against the fact that you have to 1) click to select, and 2) manipulate.  This feels strange/frustrating...seems like most other environments let you click and drag something to initiate a move. At which point it'd be selected, and you could resize/rotate/etc.

**Comment by azazdeaz** [comment]
Hi, that is right. thanks for raising this! I'm still thinking on a non hacky solution. The problem is that the component will mount only after the select MouseDown event fired. We probably have to pass this Event in the props so Transhand will know how to start the dragging operation.

**Comment by azazdeaz** [comment]
I added the new property: _grabEvent_
[Here](https://github.com/azazdeaz/transhand#api) is the description for it.
[Demo](http://azazdeaz.github.io/transhand/nested/)s are also updated.

**Comment by winkler1** [comment]
Feels much better now
