### ISSUE TITLE
v0.1.26 not working in create-react-app template

### ISSUE THREAD

**Issue by stahlmanDesign** [azazdeaz/transhand#10]
I tried to import the basic usage example into a CRA (create-react-app) project and it doesn't work.

`npm install --save transhand` installed `"transhand": "^0.1.26"` in package.json

But the app throws an error for the Transhand module:

For both the JS and CSS example I get the same error which makes me think the build is not quite right
![capture d ecran 2018-11-01 a 18 12 35](https://user-images.githubusercontent.com/972804/47883295-f23a2d80-de02-11e8-86e2-64b5f833144b.png)

**Comment by azazdeaz** [comment]
Hi, looks like @rsamec already [fixed](https://github.com/azazdeaz/transhand/commit/8c433804508cc1e44825fe5648344361644fd4b9) this, but it wasn't released on npm. Did it now, please try with v0.2.0

**Comment by stahlmanDesign** [comment]
OK thanks, it mounts now and the rect shows up in the upper-left hand part of the screen.

I can't get it to change or drag around but I'll look into the docs some more.

**Comment by stahlmanDesign** [comment]
OK, I got it working, just need to save the transform in state and update it by applying the changed properties like this:
```
state = { 
transform: { // initial position
        tx: 0, ty: 0,     //translate in px
        sx: 1, sy: 1,     //scale
        rz: 0,            //rotation in radian
        ox: 0.5, oy: 0.5, //transform origin
      }
}
```
...
```
onChange: (change) =>{
  Object.assign(change, this.state.transform)
}
```
