### ISSUE TITLE
NPM Module malformed?

### ISSUE THREAD

**Issue by youanden** [azazdeaz/transhand#7]
When I pull from npm, I don't get any src directory (maybe because .npmignore has src listed).

That means I can't run `npm run lib` to build the package, which means I can't require it.

**Comment by azazdeaz** [comment]
Hi @youanden !
If i download the transhand@0.1.19 package, this is the directory structure looks like:
.
├── lib
│   ├── CSSCoordinator.js
│   ├── CSSCoordinator.js.map
│   ├── CSSTranshand.js
│   ├── CSSTranshand.js.map
│   ├── cursorHint
│   │   ├── CursorHintDesign.js
│   │   ├── CursorHintDesign.js.map
│   │   ├── CursorHint.js
│   │   └── CursorHint.js.map
│   ├── Cursor.js
│   ├── Cursor.js.map
│   ├── DefaultCoordinator.js
│   ├── DefaultCoordinator.js.map
│   ├── fixCursorStyle.js
│   ├── fixCursorStyle.js.map
│   ├── getGlobalBoundingClientRect.js
│   ├── getGlobalBoundingClientRect.js.map
│   ├── heuristicGlobalToLocal.js
│   ├── heuristicGlobalToLocal.js.map
│   ├── index.js
│   ├── index.js.map
│   ├── TranshandDesign.js
│   ├── TranshandDesign.js.map
│   ├── Transhand.js
│   ├── Transhand.js.map
│   ├── utils.js
│   └── utils.js.map
├── package.json
└── README.md
and the package main pointing to the lib/index.js so it should be requirable.
Is it looks different for you?

**Comment by azazdeaz** [comment]
I had the same issue on an other computer and others too. I published a new version on npm (v0.1.20) and it seems to be good now. Please try to install this latest version. Sorry for the trouble!
