### ISSUE TITLE
Set draggable area

### ISSUE THREAD

**Issue by brianburkett** [azazdeaz/transhand#8]
Is there a way to set some bounding properties, so that objects can't be dragged outside of a certain range?

**Comment by azazdeaz** [comment]
Hi, you should transform the values of the onChange event before applying and feeding them back to the ```Transhand``` component.

**Comment by brianburkett** [comment]
Ah, sorry - better vernacular would be:
Can I set a container element so that objects can't be dragged or resized outside of that container?

**Comment by azazdeaz** [comment]
The answer is the same, there is no built-in functionality for this. You should implement these logics in the onChange handler function. 
```javascript
onChange(change => {
  if ('tx' in change && isInBounds(change.tx)) {
    updateX(change.tx)
  }
})
```
